security.protocol=SASL_SSL
sasl.mechanism=SCRAM-SHA-256
sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required username="qualification" password="qualification-password";
ssl.truststore.type=PEM
ssl.truststore.location=/qualification/phase13-ca.pem
